#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''

    scripts: fcm

    :author: Sam Gammon <sam@momentum.io>
    :copyright: (c) momentum labs, 2013
    :license: The inspection, use, distribution, modification or implementation
              of this source code is governed by a private license - all rights
              are reserved by the Authors (collectively, "momentum labs, ltd")
              and held under relevant California and US Federal Copyright laws.
              For full details, see ``LICENSE.md`` at the root of this project.
              Continued inspection of this source code demands agreement with
              the included license and explicitly means acceptance to these terms.

'''


# stdlib
import sys


def main(args):

  ''' Entrypoint for the ``fcm`` development utility.

      :param args: Argument list from the command line.

      :returns: Unix-style exit code - ``0`` for success,
      ``1`` or greater for failure. '''

  print "hi i am a stub"
  return 0


if __name__ == "__main__": sys.exit(main(sys.argv[:]))
